export default {
  success: true,
  data: {
    memes: [
      {
        id: '304',
        name: 'Troll face',
        url: 'images/memeimg.png',
        width: 568,
        height: 335,
        box_count: 2,
      },

      {
        id: '61579',
        name: 'One Does Not Simply',
        url: 'images/image2.jpg',
        width: 568,
        height: 335,
        box_count: 2,
      },

      {
        id: '101470',
        name: 'Ancient Aliens',
        url: 'images/image3.jpg',
        width: 500,
        height: 437,
        box_count: 2,
      },

      {
        id: 1,
        name: 'Success Kid',
        url: 'images/image4.jpg',
        width: 500,
        height: 400,
        box_count: 2,
      },
      {
        id: 2,
        name: 'Doge',
        url: 'images/image5.jpg',
        width: 600,
        height: 450,
        box_count: 1,
      },
      // {
      //   id: 3,
      //   name: 'Disaster Girl',
      //   url: 'https://example.com/disaster_girl.jpg',
      //   width: 550,
      //   height: 500,
      //   box_count: 1,
      // },
      // {
      //   id: 4,
      //   name: 'Bad Luck Brian',
      //   url: 'https://example.com/bad_luck_brian.jpg',
      //   width: 480,
      //   height: 360,
      //   box_count: 2,
      // },
      // {
      //   id: 5,
      //   name: 'Grumpy Cat',
      //   url: 'https://example.com/grumpy_cat.jpg',
      //   width: 400,
      //   height: 300,
      //   box_count: 1,
      // },
      // {
      //   id: 6,
      //   name: 'Condescending Wonka',
      //   url: 'https://example.com/condescending_wonka.jpg',
      //   width: 600,
      //   height: 400,
      //   box_count: 1,
      // },
      // {
      //   id: 7,
      //   name: 'One Does Not Simply',
      //   url: 'https://example.com/one_does_not_simply.jpg',
      //   width: 640,
      //   height: 480,
      //   box_count: 2,
      // },
      // {
      //   id: 8,
      //   name: 'First World Problems',
      //   url: 'https://example.com/first_world_problems.jpg',
      //   width: 500,
      //   height: 400,
      //   box_count: 2,
      // },
      // {
      //   id: 9,
      //   name: 'Scumbag Steve',
      //   url: 'https://example.com/scumbag_steve.jpg',
      //   width: 550,
      //   height: 400,
      //   box_count: 2,
      // },
      // {
      //   id: 10,
      //   name: 'Futurama Fry',
      //   url: 'https://example.com/futurama_fry.jpg',
      //   width: 600,
      //   height: 450,
      //   box_count: 1,
      // },
      // {
      //   id: 11,
      //   name: 'Overly Attached Girlfriend',
      //   url: 'https://example.com/overly_attached_gf.jpg',
      //   width: 480,
      //   height: 360,
      //   box_count: 2,
      // },
      // {
      //   id: 12,
      //   name: 'Ermahgerd',
      //   url: 'https://example.com/ermahgerd.jpg',
      //   width: 400,
      //   height: 300,
      //   box_count: 1,
      // },
      // {
      //   id: 13,
      //   name: 'The Most Interesting Man in the World',
      //   url: 'https://example.com/most_interesting_man.jpg',
      //   width: 640,
      //   height: 480,
      //   box_count: 1,
      // },
      // {
      //   id: 14,
      //   name: 'Distracted Boyfriend',
      //   url: 'https://example.com/distracted_boyfriend.jpg',
      //   width: 550,
      //   height: 400,
      //   box_count: 3,
      // },
      // {
      //   id: 15,
      //   name: 'That Would Be Great',
      //   url: 'https://example.com/that_would_be_great.jpg',
      //   width: 600,
      //   height: 450,
      //   box_count: 2,
      // },
      // {
      //   id: 16,
      //   name: 'Hide the Pain Harold',
      //   url: 'https://example.com/hide_the_pain_harold.jpg',
      //   width: 500,
      //   height: 400,
      //   box_count: 1,
      // },
      // {
      //   id: 17,
      //   name: 'The Rock Driving',
      //   url: 'https://example.com/the_rock_driving.jpg',
      //   width: 550,
      //   height: 500,
      //   box_count: 2,
      // },
      // {
      //   id: 18,
      //   name: 'Is This a Pigeon?',
      //   url: 'https://example.com/is_this_a_pigeon.jpg',
      //   width: 480,
      //   height: 360,
      //   box_count: 1,
      // },
      // {
      //   id: 19,
      //   name: 'Picard Facepalm',
      //   url: 'https://example.com/picard_facepalm.jpg',
      //   width: 400,
      //   height: 300,
      //   box_count: 1,
      // },
      // {
      //   id: 20,
      //   name: 'Philosoraptor',
      //   url: 'https://example.com/philosoraptor.jpg',
      //   width: 600,
      //   height: 400,
      //   box_count: 1,
      // },
    ],
  },
};
